// Code generated by github.com/fjl/gencoDEWH. DO NOT EDIT.

package tests

import (
	"encoding/json"
	"math/big"

	"github.com/DEWH/go-DEWH/common"
	"github.com/DEWH/go-DEWH/common/math"
)

var _ = (*difficultyTestMarshaling)(nil)

func (d DifficultyTest) MarshalJSON() ([]byte, error) {
	type DifficultyTest struct {
		ParentTimestamp    *math.HexOrDEWHimal256 `json:"parentTimestamp"`
		ParentDifficulty   *math.HexOrDEWHimal256 `json:"parentDifficulty"`
		UncleHash          common.Hash           `json:"parentUncles"`
		CurrentTimestamp   *math.HexOrDEWHimal256 `json:"currentTimestamp"`
		CurrentBlockNumber math.HexOrDEWHimal64   `json:"currentBlockNumber"`
		CurrentDifficulty  *math.HexOrDEWHimal256 `json:"currentDifficulty"`
	}
	var enc DifficultyTest
	enc.ParentTimestamp = (*math.HexOrDEWHimal256)(d.ParentTimestamp)
	enc.ParentDifficulty = (*math.HexOrDEWHimal256)(d.ParentDifficulty)
	enc.UncleHash = d.UncleHash
	enc.CurrentTimestamp = (*math.HexOrDEWHimal256)(d.CurrentTimestamp)
	enc.CurrentBlockNumber = math.HexOrDEWHimal64(d.CurrentBlockNumber)
	enc.CurrentDifficulty = (*math.HexOrDEWHimal256)(d.CurrentDifficulty)
	return json.Marshal(&enc)
}

func (d *DifficultyTest) UnmarshalJSON(input []byte) error {
	type DifficultyTest struct {
		ParentTimestamp    *math.HexOrDEWHimal256 `json:"parentTimestamp"`
		ParentDifficulty   *math.HexOrDEWHimal256 `json:"parentDifficulty"`
		UncleHash          *common.Hash          `json:"parentUncles"`
		CurrentTimestamp   *math.HexOrDEWHimal256 `json:"currentTimestamp"`
		CurrentBlockNumber *math.HexOrDEWHimal64  `json:"currentBlockNumber"`
		CurrentDifficulty  *math.HexOrDEWHimal256 `json:"currentDifficulty"`
	}
	var DEWH DifficultyTest
	if err := json.Unmarshal(input, &DEWH); err != nil {
		return err
	}
	if DEWH.ParentTimestamp != nil {
		d.ParentTimestamp = (*big.Int)(DEWH.ParentTimestamp)
	}
	if DEWH.ParentDifficulty != nil {
		d.ParentDifficulty = (*big.Int)(DEWH.ParentDifficulty)
	}
	if DEWH.UncleHash != nil {
		d.UncleHash = *DEWH.UncleHash
	}
	if DEWH.CurrentTimestamp != nil {
		d.CurrentTimestamp = (*big.Int)(DEWH.CurrentTimestamp)
	}
	if DEWH.CurrentBlockNumber != nil {
		d.CurrentBlockNumber = uint64(*DEWH.CurrentBlockNumber)
	}
	if DEWH.CurrentDifficulty != nil {
		d.CurrentDifficulty = (*big.Int)(DEWH.CurrentDifficulty)
	}
	return nil
}
