// Code generated by github.com/fjl/gencoDEWH. DO NOT EDIT.

package whisperv5

import (
	"encoding/json"

	"github.com/DEWH/go-DEWH/common/hexutil"
)

var _ = (*criteriaOverride)(nil)

func (c Criteria) MarshalJSON() ([]byte, error) {
	type Criteria struct {
		SymKeyID     string        `json:"symKeyID"`
		PrivateKeyID string        `json:"privateKeyID"`
		Sig          hexutil.Bytes `json:"sig"`
		MinPow       float64       `json:"minPow"`
		Topics       []TopicType   `json:"topics"`
		AllowP2P     bool          `json:"allowP2P"`
	}
	var enc Criteria
	enc.SymKeyID = c.SymKeyID
	enc.PrivateKeyID = c.PrivateKeyID
	enc.Sig = c.Sig
	enc.MinPow = c.MinPow
	enc.Topics = c.Topics
	enc.AllowP2P = c.AllowP2P
	return json.Marshal(&enc)
}

func (c *Criteria) UnmarshalJSON(input []byte) error {
	type Criteria struct {
		SymKeyID     *string        `json:"symKeyID"`
		PrivateKeyID *string        `json:"privateKeyID"`
		Sig          *hexutil.Bytes `json:"sig"`
		MinPow       *float64       `json:"minPow"`
		Topics       []TopicType    `json:"topics"`
		AllowP2P     *bool          `json:"allowP2P"`
	}
	var DEWH Criteria
	if err := json.Unmarshal(input, &DEWH); err != nil {
		return err
	}
	if DEWH.SymKeyID != nil {
		c.SymKeyID = *DEWH.SymKeyID
	}
	if DEWH.PrivateKeyID != nil {
		c.PrivateKeyID = *DEWH.PrivateKeyID
	}
	if DEWH.Sig != nil {
		c.Sig = *DEWH.Sig
	}
	if DEWH.MinPow != nil {
		c.MinPow = *DEWH.MinPow
	}
	if DEWH.Topics != nil {
		c.Topics = DEWH.Topics
	}
	if DEWH.AllowP2P != nil {
		c.AllowP2P = *DEWH.AllowP2P
	}
	return nil
}
